apiVersion: 1

contactPoints:
  - name: email-notifications
    receivers:
      - uid: email-receiver
        type: email
        settings:
          addresses: antonito.rodriguez42@gmail.com
          singleEmail: true
          subject: |
            [Grafana Alert] {{ .CommonLabels.alertname }}
          message: |
            {{ range .Alerts }}
            Estado: {{ .Status }}
            Resumen: {{ .Annotations.summary }}
            Descripci√≥n: {{ .Annotations.description }}
            {{ end }}
