global:
    scrape_interval: 15s

scrape_configs:
    - job_name: 'weather-api'
      static_configs:
          # Configuraci√≥n con docker compose (por defecto)
          - targets: ['weather-app:9464']

          # Para desarrollo local, descomenta:
          # - targets: ['host.docker.internal:9464']
