services:

  devdays-proxy:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  devdays-frontend:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    networks:
      - backend

  devdays-app:
    image: devdays-app:latest
    restart: unless-stopped
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongodb:27017/isadevdays2025
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "${HOST_PORT:-3000}:3000"
    networks:
      - backend
      - devdays-network

networks:
  backend:
  devdays-network:
    external: true